// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_rt_CPlusToCSharp_1_H
#define WINRT_rt_CPlusToCSharp_1_H
#include "winrt/impl/rt_CPlusToCSharp.0.h"
WINRT_EXPORT namespace winrt::rt_CPlusToCSharp
{
    struct __declspec(empty_bases) ITest :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ITest>
    {
        ITest(std::nullptr_t = nullptr) noexcept {}
        ITest(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
