// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.211028.7

#pragma once
#ifndef WINRT_rt_CPlusToCSharp_2_H
#define WINRT_rt_CPlusToCSharp_2_H
#include "winrt/impl/rt_CPlusToCSharp.1.h"
WINRT_EXPORT namespace winrt::rt_CPlusToCSharp
{
    struct __declspec(empty_bases) Test : winrt::rt_CPlusToCSharp::ITest
    {
        Test(std::nullptr_t) noexcept {}
        Test(void* ptr, take_ownership_from_abi_t) noexcept : winrt::rt_CPlusToCSharp::ITest(ptr, take_ownership_from_abi) {}
        Test();
    };
}
#endif
